Repository opticSquid/hive, pull requests merged in 2022-01, with the labels that each got.

#8 Next
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/App.yml
  .github/workflows/Server.yml
  .github/workflows/Website.yml
  .github/workflows/codeql-analysis.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: documentation

#10 Merging next branch with main branch many documentation updated
  .github/ISSUE_TEMPLATE.md/bug_report.md
  .github/ISSUE_TEMPLATE.md/feature_request.md
  Assets/jwoc_logo.svg
  README.md
Labels: documentation, Medium

#18 removing hashes from rgb color codes of issue labels
  .github/labels.json
Labels: documentation

#14 Update README.md
  README.md
Labels: JWOC, medium, documentation
