Repository opticSquid/hive, pull requests merged in 2022-02, with the labels that each got.

#19 Brining the next and main branch to same level and with a emergency bug patch
  .github/workflows/issue-watcher.yml
  README.md
Labels: documentation, bug

#32 Removing faulty issue templates
  .github/ISSUE_TEMPLATE.md/bug_report.md
  .github/ISSUE_TEMPLATE.md/feature_request.md
Labels: JWOC, bug

#34 Issue #27 :- Cleaned React app to start state
  Website/.eslintcache
  Website/.gitignore
  Website/README.md
  Website/package-lock.json
  Website/package.json
  Website/src/App.css
  Website/src/App.js
  Website/src/Components/Error.js
  Website/src/Components/FbLogin.js
  Website/src/Components/HomePage.js
  Website/src/Components/HomePageContent.js
  Website/src/Components/Login.js
  Website/src/Components/SignUp.js
  Website/src/Static/stop-orig.jpg
  Website/src/Static/stop.jpg
  Website/src/Themes/DefaultTheme.js
  Website/src/logo.svg
Labels: JWOC, easy, help wanted

#33 Add discord badge
  README.md
Labels: JWOC, easy, documentation

#35 Cleaning up react website
  Website/.eslintcache
  Website/.gitignore
  Website/README.md
  Website/package-lock.json
  Website/package.json
  Website/src/App.css
  Website/src/App.js
  Website/src/Components/Error.js
  Website/src/Components/FbLogin.js
  Website/src/Components/HomePage.js
  Website/src/Components/HomePageContent.js
  Website/src/Components/Login.js
  Website/src/Components/SignUp.js
  Website/src/Static/stop-orig.jpg
  Website/src/Static/stop.jpg
  Website/src/Themes/DefaultTheme.js
  Website/src/logo.svg
Labels: JWOC

#30 Updated README.md file
  README.md
Labels: JWOC, medium, good first issue

#42 Implemented Authentication
  Server/.env.sample
  Server/Database/ActiveSession.js
  Server/Database/FbUsers.js
  Server/Database/Users.js
  Server/Features/UserNameGenerator.js
  Server/Features/features.js
  Server/Routes/Login.js
  Server/Routes/SignUp.js
  Server/Routes/Third Party Logins/3rdpaty.js
  Server/Routes/Third Party Logins/FbLogin.js
  Server/Routes/Users.js
  Server/db/config.js
  Server/index.js
  Server/middleware/rateLimiter.js
  Server/models/User.js
  Server/package-lock.json
  Server/package.json
  Server/routes/auth.js
  Server/server.cert
  Server/server.key
  Server/utils/jwt_helper.js
  Server/utils/validation_schema.js
Labels: JWOC, hard
